TITLE_X_START = 5
TITLE_Y_START = 12

TITLE_N_START = 0
TITLE_I_START = 6
TITLE_B1_START = 8
TITLE_B2_START = 12
TITLE_L_START = 16
TITLE_E_START = 20
TITLE_S_START = 24
# [TITLE_X_START + 0, TITLE_Y_START + 0]
TITLE = [
  [TITLE_X_START + TITLE_N_START + 0, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_N_START + 0, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_N_START + 0, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_N_START + 0, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_N_START + 0, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_N_START + 1, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_N_START + 2, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_N_START + 3, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_N_START + 4, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_N_START + 4, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_N_START + 4, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_N_START + 4, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_N_START + 4, TITLE_Y_START + 4],

  [TITLE_X_START + TITLE_I_START + 0, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_I_START + 0, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_I_START + 0, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_I_START + 0, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_I_START + 0, TITLE_Y_START + 4],

  [TITLE_X_START + TITLE_B1_START + 0, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_B1_START + 0, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_B1_START + 0, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_B1_START + 0, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_B1_START + 0, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_B1_START + 1, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_B1_START + 1, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_B1_START + 1, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_B1_START + 2, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_B1_START + 2, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_B1_START + 2, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_B1_START + 2, TITLE_Y_START + 4],

  [TITLE_X_START + TITLE_B2_START + 0, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_B2_START + 0, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_B2_START + 0, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_B2_START + 0, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_B2_START + 0, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_B2_START + 1, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_B2_START + 1, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_B2_START + 1, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_B2_START + 2, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_B2_START + 2, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_B2_START + 2, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_B2_START + 2, TITLE_Y_START + 4],

  [TITLE_X_START + TITLE_L_START + 0, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_L_START + 0, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_L_START + 0, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_L_START + 0, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_L_START + 0, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_L_START + 1, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_L_START + 2, TITLE_Y_START + 0],

  [TITLE_X_START + TITLE_E_START + 0, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_E_START + 0, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_E_START + 0, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_E_START + 0, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_E_START + 0, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_E_START + 1, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_E_START + 1, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_E_START + 1, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_E_START + 2, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_E_START + 2, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_E_START + 2, TITLE_Y_START + 4],

  [TITLE_X_START + TITLE_S_START + 0, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_S_START + 0, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_S_START + 0, TITLE_Y_START + 3],
  [TITLE_X_START + TITLE_S_START + 0, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_S_START + 1, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_S_START + 1, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_S_START + 1, TITLE_Y_START + 4],
  [TITLE_X_START + TITLE_S_START + 2, TITLE_Y_START + 0],
  [TITLE_X_START + TITLE_S_START + 2, TITLE_Y_START + 1],
  [TITLE_X_START + TITLE_S_START + 2, TITLE_Y_START + 2],
  [TITLE_X_START + TITLE_S_START + 2, TITLE_Y_START + 4]
]

class Scene
  def self.render_title(game)
    game.outputs.labels << {
      x: (game.grid.w / 2),
      y: (game.grid.h / 2) - 50,
      text: "Press Spacebar to Start",
      size_enum: 4,
      alignment_enum: 1,
    }.merge(COLOR_TEXT_DARK)

    Block.render(game, TITLE)
  end

  def self.render_gameover(game)
    game.outputs.labels << {
      x: (game.grid.w / 2),
      y: (game.grid.h / 2),
      text: "Game Over",
      size_enum: 8,
      alignment_enum: 1
    }.merge(COLOR_TEXT_DARK)

    game.outputs.labels << {
      x: (game.grid.w / 2),
      y: (game.grid.h / 2) - 50,
      text: "Score: #{game.state.score}",
      size_enum: 4,
      alignment_enum: 1
    }.merge(COLOR_TEXT_DARK)

    game.outputs.labels << {
      x: (game.grid.w / 2),
      y: (game.grid.h / 2) - 150,
      text: "Press Spacebar to Play Again",
      size_enum: 4,
      alignment_enum: 1
    }.merge(COLOR_TEXT_DARK)
  end
end
